### ISSUE TITLE
Random empty documentation and missing images

### ISSUE THREAD

**Issue by aggsol** [vala-lang/valadoc-org#281] opened 2020-03-13 08:27 UTC
**Describe the bug**

GIO 2.0 documentation is empty

**To Reproduce**

1. Go to https://valadoc.org/gio-2.0/index.htm
2. See empty page

**Expected behavior**
valadoc.org should provide complete documenation of GIO

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser:  Firefox 74

**Comment by ricotz** [comment] 2020-03-13 14:39
There are many empty pages not just for gio-2.0

**Comment by benwaffle** [comment] 2020-03-13 15:00
Are these docs able to be generated locally? Or is this bug only in the valadoc.org deployment

**Comment by btkostner** [comment] 2020-03-13 17:35
Seems valadoc is just failing to run:

```
===== gstreamer-rtsp-server-1.0 =====
  run valadoc ...
valadoc --target-glib 2.98 --importdir girs --doclet "." -o "tmp/gstreamer-rtsp-server-1.0" "/usr/share/vala-0.48/vapi/gstreamer-rtsp-server-1.0.vapi" --vapidir "/usr/share/vala-0.48/vapi" --girdir "girs/gir-1.0"  --use-svg-images --importdir "girs/gir-1.0" --import GstRtspServer-1.0 --metadatadir documentation/gstreamer-rtsp-server-1.0 --wiki documentation/gstreamer-rtsp-server-1.0/wiki
ERROR: Can't generate documentation for gstreamer-rtsp-server-1.0.
```

**Comment by btkostner** [comment] 2020-03-13 17:43
Updating to ubuntu 20.04 for Dockerfile, and using the _non_ bleeding edge vala team ppa. Will report back.

**Comment by ricotz** [comment] 2020-03-13 18:40
Caused by https://gitlab.gnome.org/GNOME/vala/-/commit/aff7099d4a06c1022255cf85c5632e86ec9df1c9

This issue should be fixed by https://gitlab.gnome.org/GNOME/vala/-/commit/ccf932f616dc60b856a37f28924b35e52d3d4e83

Sorry about that.

**Comment by tintou** [comment] 2020-03-13 19:17
> Are these docs able to be generated locally? Or is this bug only in the valadoc.org deployment

For informational purposes, the GitHub Action in this repository is creating the Docker container: https://github.com/vala-lang/valadoc-org/actions?query=workflow%3APublish

**Comment by ricotz** [comment] 2020-03-15 09:03
This got fixed with the last update of https://hub.docker.com/r/valalang/docs

**Closed by ricotz** 2020-03-15 09:03 UTC
Labels: Priority Critical
