### ISSUE TITLE
Blank pages for SDL2

### ISSUE THREAD

**Issue by lxmcf** [vala-lang/valadoc-org#278] opened 2020-02-23 03:10 UTC
**Describe the bug**
When trying to open the documentation for anything related to SDL2 (sdl2-net, sdl2-gfx, etc) will return a completely blank page and nothing will show up when searching from SDL2 components.

**To Reproduce**
1. Go to https://valadoc.org/sdl2/index.htm
2. See error

**Expected behavior**
Should normally just load up the documents

**Comment by aggsol** [comment] 2020-03-13 08:29
I need this to work. I use valadoc.org daily.

**Comment by ricotz** [comment] 2020-03-13 15:19
Duplicate of #281

**Closed** 2020-03-19 07:56 UTC
